name: Toffi Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  toffi-build:
    strategy:
      matrix:
        os: ubuntu-latest
        build_type: Release
        compiler: gcc

        os: macos-latest
        build_type: Release
        compiler: clang

        os: windows-latest
        build_type: Release
        compiler: msvc

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: |
        cmake --build build --config ${{ matrix.build_type }} --parallel