name: Toffi Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  toffi-build:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            compiler: gcc
          - os: windows-latest
            compiler: msvc
          - os: macos-latest
            compiler: clang

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-timeout: 10

    - name: Install Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libx11-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libudev-dev \
          libgl1-mesa-dev \
          libfreetype6-dev \
          libopenal-dev \
          libflac-dev \
          libvorbis-dev \
          libglu1-mesa-dev

    - name: cmake config
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: build
      run: |
        cmake --build build --config ${{ matrix.build_type }} --parallel
        